const FETCH_BOARD_START = 'FETCH_BOARD_START';
const FETCH_BOARD_SUCCESS = 'FETCH_BOARD_SUCCESS';
const FETCH_BOARD_ERROR = 'FETCH_BOARD_ERROR';
const ADD_NEW_COLUMN = 'ADD_NEW_COLUMN';
const ADD_NEW_CARD = 'ADD_NEW_CARD';
const ADD_DESCRIPTION = 'ADD_DESCRIPTION';

export {
  FETCH_BOARD_START,
  FETCH_BOARD_SUCCESS,
  FETCH_BOARD_ERROR,
  ADD_NEW_COLUMN,
  ADD_NEW_CARD,
  ADD_DESCRIPTION
}
