const FETCH_BOARD_START = 'FETCH_BOARD_START';
const FETCH_BOARD_SUCCESS = 'FETCH_BOARD_SUCCESS';
const FETCH_BOARD_ERROR = 'FETCH_BOARD_ERROR';

const ADD_NEW_COLUMN = 'ADD_NEW_COLUMN';
const ADD_NEW_CARD = 'ADD_NEW_CARD';
const ADD_DESCRIPTION = 'ADD_DESCRIPTION';

const RENAME_COLUMN = 'RENAME_COLUMN';
const REMOVE_COLUMN = 'REMOVE_COLUMN';

const RENAME_CARD = 'RENAME_CARD';
const REMOVE_CARD = 'REMOVE_CARD';

const ADD_TODOS_TITLE = 'ADD_TODOS_TITLE';
const ADD_TODO = 'ADD_TODO';
const SET_TODO_COMPLETE = 'SET_TODO_COMPLETE';
const REMOVE_TODO = 'REMOVE_TODO';
const CHANGE_TODO_TITLE = 'CHANGE_TODO_TITLE';
const CHANGE_TODOS_TITLE = 'CHANGE_TODOS_TITLE';

const SET_DATE = 'SET_DATE';

export {
  FETCH_BOARD_START,
  FETCH_BOARD_SUCCESS,
  FETCH_BOARD_ERROR,
  ADD_NEW_COLUMN,
  ADD_NEW_CARD,
  ADD_DESCRIPTION,
  RENAME_COLUMN,
  REMOVE_COLUMN,
  RENAME_CARD,
  REMOVE_CARD,
  ADD_TODOS_TITLE,
  ADD_TODO,
  SET_TODO_COMPLETE,
  REMOVE_TODO,
  CHANGE_TODO_TITLE,
  CHANGE_TODOS_TITLE,
  SET_DATE
}
