const FETCH_BOARD_START = 'FETCH_BOARD_START';
const FETCH_BOARD_SUCCESS = 'FETCH_BOARD_SUCCESS';
const FETCH_BOARD_ERROR = 'FETCH_BOARD_ERROR';

const SET_CURRENT_USER = 'SET_CURRENT_USER';

const ADD_NEW_COLUMN = 'ADD_NEW_COLUMN';
const RENAME_COLUMN = 'RENAME_COLUMN';
const REMOVE_COLUMN = 'REMOVE_COLUMN';

const ADD_NEW_TASKLIST = 'ADD_NEW_TASKLIST';
const RENAME_TASKLIST = 'RENAME_TASKLIST';
const REMOVE_TASKLIST = 'REMOVE_TASKLIST';

const ADD_DESCRIPTION = 'ADD_DESCRIPTION';

const ADD_TODOS_TITLE = 'ADD_TODOS_TITLE';
const ADD_TODO = 'ADD_TODO';
const SET_TODO_COMPLETE = 'SET_TODO_COMPLETE';
const REMOVE_TODO = 'REMOVE_TODO';
const CHANGE_TODO_TITLE = 'CHANGE_TODO_TITLE';
const CHANGE_TODOS_TITLE = 'CHANGE_TODOS_TITLE';

const SET_DATE = 'SET_DATE';

const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';
const REMOVE_COMMENT = 'REMOVE_COMMENT';
const EDIT_COMMENT = 'EDIT_COMMENT';

const ADD_TAG = 'ADD_TAG';
const REMOVE_TAG = 'REMOVE_TAG';

const ATTACH_USER_TO_TASK = 'ATTACH_USER_TO_TASK';
const REMOVE_USER_FROM_TASK = 'REMOVE_USER_FROM_TASK';

export {
  FETCH_BOARD_START,
  FETCH_BOARD_SUCCESS,
  FETCH_BOARD_ERROR,
  ADD_NEW_COLUMN,
  ADD_NEW_TASKLIST,
  ADD_DESCRIPTION,
  RENAME_COLUMN,
  REMOVE_COLUMN,
  RENAME_TASKLIST,
  REMOVE_TASKLIST,
  ADD_TODOS_TITLE,
  ADD_TODO,
  SET_TODO_COMPLETE,
  REMOVE_TODO,
  CHANGE_TODO_TITLE,
  CHANGE_TODOS_TITLE,
  SET_DATE,
  SET_CURRENT_USER,
  ADD_NEW_COMMENT,
  REMOVE_COMMENT,
  EDIT_COMMENT,
  ADD_TAG,
  REMOVE_TAG,
  ATTACH_USER_TO_TASK,
  REMOVE_USER_FROM_TASK
}
